backend:
  name: github
  repo: offcourse/offcourse-studio

media_folder: static/img
public_folder: /img

collections:
  - name: "homepage"
    label: "homepage"
    folder: "content/homepage"
    create: true
    fields:
      - { label: "SectionTitle", name: "title", widget: "list" }
      - { label: "SectionRole", name: "role", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
